# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        miniature:
            quality: 75
            filters:
                thumbnail:
                    size: [400, 400]
                    mode: outbound
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [800, 500]
                    mode: outbound
        wall:
            quality: 75
            filters:
                thumbnail:
                    size: [1200, 400]
                    mode: outbound
        slide:
            quality: 75
            filters:
                thumbnail:
                    size: [2720, 1400]
                    mode: outbound
        home:
            quality: 75
            filters:
                thumbnail:
                    size: [685, 198]
                    mode: outbound
