vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: /images/products
           upload_destination: '%kernel.project_dir%/public/images/products'
       freelance_cv:
           uri_prefix: /cv
           upload_destination: '%kernel.project_dir%/public/cv'